### ISSUE TITLE
EPIC: Reduce number of processes spawned by `EdgeDeletionAnalyzer` by writing all graphs-minus-one-edge into single `.g6` file

### ISSUE THREAD

**Issue by wbkboyer** [graph-algorithms/edge-addition-planarity-suite#110]
Windows suffers from an issue where the Page Table Entries balloon when we spawn literal billions of processes (discovered during #108). We could significantly reduce the number of processes spawned (by $O\(numNonPlanarGraphsWithNoFoundK33ForM \times M\)$ for each edge-count) by simplifying and batching the test for the target homeomorph in all graph-minus-one-edge per graph in the input file (all graphs of a given order and edge-count).

- [ ] After #109 is finished, re-run the test table generation for `K_{3,3}` search on `N=10` with `numInvalidOKs` to obtain the "EDA Proc Time" ([process time](https://docs.python.org/3/library/time.html#time.process_time)) and "EDA Total Time" ([wall time](https://docs.python.org/3/library/time.html#time.perf_counter)) as a baseline for how long EDA takes before the refactor
- [ ] Implement `.g6` Read Iterator and Write Iterator in Python
- [ ] Refactor `EdgeDeletionAnalyzer`'s `analyze_graphs()` to leverage `.g6` Read Iterator so that we no longer have to transform the graph to an adjacency list before analysis
- [ ] Refactor `EdgeDeletionAnalyzer`'s `_edge_deletion_analysis()` so that after we `deepcopy` the original graph and sequentially remove an edge, we encode the graph as `.g6` and append to a `.g6` file containing all graphs-minus-one-edge before then *only* running `TestAllGraphs()` for the given graph algorithm command (i.e. the target homeomorph search) on all of those graphs-minus-one-edge and observing whether `NONEMBEDDABLE` is nonzero.

**Comment by john-boyer-phd** [comment]
Thank you for fleshing out the idea we briefly discussed on a first videoconference. Now that we have had a chance to discuss this fleshed-out version, we have concluded  that it will not give us as much optimization as we had hoped because it will only optimize performance on graphs that are found not to have a `K_{3,3}` (small percentage) and also are not planar (even smaller percentage).
