### ISSUE TITLE
EPIC: Support digraph6 file format

### ISSUE THREAD

**Issue by john-boyer-phd** [graph-algorithms/edge-addition-planarity-suite#29]
Nauty supports output of a ["digraph6" or ".d6" file format](https://users.cecs.anu.edu.au/~bdm/data/formats.txt) for digraphs. 

- [ ] Implement a reader for this format in `gp_Read()`. Ensure that the GRAPHFLAG_DIRECTEDEDGEDETECTED flag is set if the graph being read has a directed edge in it (i.e., ensure you are using `gp_SetDirection()`).
- [ ] Implement a writer for this format in `gp_Write()`. Be sure to early-out return`NOTOK` if the graph's `GRAPHFLAG_PARALLELEDGEDETECTED` flag is set.
- [ ] Add D6 support to transformation capability. When transforming a graph into the "digraph6" format, the letter 'd' is used, i.e.,  `planarity -t [-q] C|-td I O`.
- [ ] Implement read and write iterators with the same APIs as for the current "graph6" support, except using the prefix `d6` instead of `g6`.

For the above, use the same file structure as was used for "graph6" support, including addition of the project copyright statement into the files and addition of the files to the proper locations in `makefile.am`.

The testing below uses the `Petersen.digraph.txt` sample created in #254. 

Add a second submethod call (test) into `runDigraphTests()` to do the following:
- Read `Petersen.digraph.txt` into a graph G
- Write G to string in D6 format
- Read the D6 string int a graph G<sub>1</sub>
- Verify that G and G<sub>1</sub> are the same. It may be that the D6 transformation reorders the adjacencies, so it may be necessary to generate the expected output to adjacency list, hand validate that it is logically equivalent to `Petersen.digraph.txt`, and then store it in the samples. 

Add a third subfunction test `runDigraphTests()` intended to test the read and write iterators for D6 as follows:
- Open a G6 read from file iterator and D6 write to string iterator. Read `n8.mAll.g6` and, for each graph, invoke `gp_ClearEdgeDirectionFlags()`, then write to the D6 iterator. 
- Use a D6 read from string iterator to read the D6 string generated above. For each graph, run planarity with `gp_Embed()` then `gp_TestEmbedResultIntegrity()` and no `NOTOK` results from either. Count the number of OK and NONEMBEDDABLE results and verify that the counts match expectations (6966 and 5380).
