### ISSUE TITLE
Story in Epic 10: Remediate ErrorMessage(), Message(), and quiet mode flag

### ISSUE THREAD

**Issue by john-boyer-phd** [graph-algorithms/edge-addition-planarity-suite#35]
Part of Epic #10.

The new G6 read code identifies the numerous possible file format errors and (correctly) outputs helpful error messages to help a user diagnose the problem with a given G6 file. The `ErrorMessage()` method defined in `planarity.h` is used. The problem is that all `planarity*` files are logically at the application level, and all other files are at the API library level. 

- [ ] Create an `apiutils.c` and `apiutils.h` file pair. Move `ErrorMessage()` and `Message()` to `apiutils.c` with extern C declarations in `apiutils.h`.
- [ ] Move quiteMode into `apiutils.c` and change to boolean. Default `false` to match current setting.
- [ ] Create get and set quiet mode boolean methods in `apiutils.c` with extern C declarations in `apiutils.h`.
- [ ] Change `ErrorMessage()` and `Message()` to use the quite mode getter method.
- [ ] Change all other uses of quiteMode to instead use the getter and setter methods.
- [ ] Add the include for `apiutils.h` into `appconst.h`
- [ ] Remove `planarity.h` include from the g6 files
- [ ] Remediate all `ErrorMessage(Line)` calls to use a locally declared `Line` string or a static string. Some errors could be a little less informative, so the `sprintf` that constructs their content can be removed and `Line` can be replaced with an edited version of the format string for the `sprintf` (devoid of the formatting parts). Most other occurrences of `Line` can be locally declared with static size large enough to fit the largest possible content. If any must be dynamic in size, it's necessary to use `malloc()` and `free()` to maintain compilability with the MSVC C89 compiler.

**Comment by wbkboyer** [comment]
I've got a couple of questions:

1. Should `FlushConsole` and `Prompt` declarations and definitions also be moved into `apiutils.h/.c`?
2. Should we still be using `#define MAXLINE 1024`, and therefore also move it into `apiutils.h`? This is only used by:
  * `legacyCommandLine()` of `planarityCommandLine.c` - determine what error message to `sprintf()` when the file path provided in `argv[1]` is too long)
  * `beginG6ReadIterationFromG6FilePath()` of `g6-read-iterator.c` - only read up to `MAXLINE - strlen(formatStr)` characters of the `g6FilePath` when constructing the error message)
3. When you say "Add the include for `apiutils.h` into `appconst.h`", is this enough to ensure any part of the project has access to the `Message` and `ErrorMessage` functionality? I went on a bit of a detour and followed [this StackOverflow reply](https://stackoverflow.com/a/3074323/5456879)'s advice to use [cinclude2dot](https://www.flourish.org/cinclude2dot/) in conjunction with [graphviz](https://graphviz.org/) to produce this image of the `#include` directives:
  ![output](https://github.com/graph-algorithms/edge-addition-planarity-suite/assets/1198214/b5feaf62-f08b-4714-8314-e2b288a90399)
  It seems so especially due to `appconst.h` > `graphStructures.h` > `graph.h`, but I'm not sure how else to verify this...

**Comment by john-boyer-phd** [comment]
1. No, `Prompt()` is more of an application-level thing, and `FlushConsole()` is also used only at the planarity application level. Error messages are needed more broadly.
2. Remove MAXLINE and refactor. For example, the spot in `legacyCommandLine()` is ultimately one of those `ErrorMessage()` refactorings anyway.
3. Yep, I had a look into this as part of writing the spec, and the inclusion path you identified gets pretty much everywhere. (Best to ask though, since spec writers make mistakes too ^_^)
