### ISSUE TITLE
Story in Epic 10: Update Autotools Build Files

### ISSUE THREAD

**Issue by john-boyer-phd** [graph-algorithms/edge-addition-planarity-suite#36]
This is part of Epic #10. 

Several files have been added as part of adding API support for `.g6` files in prior stories. These include read and write iterators, api utils, and new planarity app level files. 

- [ ] The `Makefile.am` should be updated to reflect the additional files.

- [ ]  The `Makefile.am` in the `samples` directory should be updated if there are any new sample files.

- [ ] We will wait to update `Configure.ac` until the story for preparing the release, at which point we will need to update the planarity version in AC_INIT and also the three `LT_*` changes to be made.

- [ ] On Windows, test the distribution make sequence (per the readme instructions, this starts with going into `bash` and `autogen.sh` and ends with `make distcheck`). This will include a successful smoke test after a successful build, proving that the correct files were all added to the two `Makefile.am` files above.

- [ ] Optionally, also test distribution make sequence on Linux.
