### ISSUE TITLE
Epic: Improve Graph Read/Write Error Detection and Reporting

### ISSUE THREAD

**Issue by john-boyer-phd** [graph-algorithms/edge-addition-planarity-suite#37]
There are several improvements that can be made throughout the `graphIO.c` code:

- [ ] All instances of `return NOTOK` and `RetVal = NOTOK` should be preceded with an explanatory `ErrorMessage()` to indicate what has gone wrong, in keeping with the level of information now provide by the new "graph6" reader. For example, there should be an error message in `_ReadAdjList()` that indicates loop edges are not supported (until/unless they are). 
- [ ] The adjacency matrix reader should be amended to detect the failure of `fscanf()` and `sscanf()` as well as successful reading of integer values other than 0 and 1, and provide an appropriate `ErrorMessage()` and `return NOTOK` when such events occur.
- [ ] Amend `ReadAdjList()` and `_ReadLEDAGraph()` to efficiently detect and report an error  and `return NOTOK` if parallel edges are detected (until/unless those are supported).
- [ ] Amend the LEDA graph format reader to detect a loop edge and report an error and `return NOTOK`
- [ ] Amend `_WriteAdjMatrix()` and the new "graph6" writer to report an error and `return NOTOK` if the graph being written is a digraph.
