### ISSUE TITLE
EPIC: Source Code Reorganization

### ISSUE THREAD

**Issue by john-boyer-phd** [graph-algorithms/edge-addition-planarity-suite#91]
The source code for `planarity` needs to be reorganized to make easier to navigate and to reuse the relevant APIs in other projects in other repositories. At each step:

- various include files and include directives will need to be amended to restore compilation ability.  
- it will be necessary to amend `Makefile.am` and the developer project files for VS Code and Eclipse to restore and test all compile, run, `make dist`, `make install`, and `man` capabilities. 
- The template development environment files will need to be updated, if they exist (per solution to #89).

- [x] `planarity.c` should be reduced to just containing `main()`. All other code should be moved out to new files. Make a new file `planarityMenu.c` for all the methods below `main()` that are about the menu, and make `planarityHelp.c` for all the methods above `main()`. 
- [x] Move all files starting with `planarity` into a subdirectory called `planarityApp`. Ideally this would even include `planarity.c` and `planarity.1`
- [x] Move all files starting with `graph`, `g6`, `ap`, `li`, `st`, and `platform` into a `graphLib` directory. 
- [x] Within `graphLib`, create an `io` directory for `graphIO.c`, all `g6` files, and files starting with `str`.
- [x] Within `graphLib`, create a `lowlevelUtils` directory for files starting with `ap`, `stack`, `li`, and `platform`.
- [x] Within `graphLib`, create a `extensionSystem` directory for files starting with `graphExtensions` and `graphFunctionTable.h` 
- [x] Within `graphLib`, create a `homeomorphSearch` directory for all files starting with `graphK`
- [x] Within `graphLib`, create a `planarityRelated` directory for `graphEmbed.c`, `graphIsolator.c`, `graphNonplanar.c`, `graphOuterplanarObstruction.c`, `graphTests.c` and all files starting with `graphDrawPlanar`
- [x] In `Makefile.am`, pull the planarityApp files out of libPlanarity sources and put them into planarity sources (we will need to deal with a different version number update to libPlanarity later, as a separate issue).
- [x] Removed wiki update task because it would be better to have the code reorg merged to main before editing the wiki to talk about the structure, so separate issue, #97.
- [x] Within `graphLib` add a file called `graphLib.h` and use the copyright message, `#ifndef` protection, and `extern C` encapsulation. Inside the `extern C` envelope, do the includes currently shown on lines 14 through 24 of `planarity.h`.
- [x] Within `planarity.h`, change the includes on lines 14-24 to instead include `graphLib.h`
